### ISSUE TITLE
Add a revision number or letter to the New changed files created...

### ISSUE THREAD

**Issue by CryptonightCanada** [plenteum/plenteum#9]
The titles on both the buggy files and the new ones you revised are all the same (might be in order where its published on github but there is nothing to identify or distinguish the files once they are moved from your repository....   (ex. browsers will usually download everything into the Download folder,,,,, but these have an identical evil buggy twin that could be mistaken for the latest release).... I see your newest title on github has clearly '- Bug Fix' but there isnt anything to make it effective to tell a difference outside the repo....    I suggest adding a -b  to each of the latest releases.. or do it backwards and put a -B on the buggy files but make sure you identify thats why its there

**Comment by davehlong** [comment]
Hi 

I actually replaced the buggy files on the v0.4.0 release with the updated ones per the comment on the latest release: 
`Binaries for Both Releases (this one and v0.4.0 below) have been updated.`
so no buggy files can be downloaded from the release tab anymore.

I realise this is not the best way to handle it and should this ever occur in future (hopefully it won't) - I'll try remember to update the actual version number in the software itself before publishing the update (I was scrambling a bit with limited connectivity on Easter Friday and my wife was on my case :-)) and simply forgot to do this, which is why I replaced the actual binaries on the old release to avoid someone downloading the old buggy version.

**Comment by TunercarZ** [comment]
Hi Dave,
Thanks for the reply and updates; no, worries!
The day after easter, I had an electrical fire from my oven, soot damage took out my 3 cpus and I just finally got one up again. haha 

Yepper's on the file update... in my instance; i was operating on a buggy linux mint with Nvidia drivers and so my computer was confused as to which file was which.. Perhaps I was, never the mind.. I thank you again!
